services:
  database:
    container_name: database
    image: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_secret
      LANG: C.UTF-8
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - net
    healthcheck:
      interval: 5s
      test: (mysqladmin ping --silent && exit 1) || echo 0
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - net
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend.dockerfile
    environment:
      TEXT_MODERATION: false
    ports:
      - "8080:8080"
    networks:
      - net
    volumes:
      - backend_data:/app/images
    depends_on:
      database:
        condition: service_healthy
volumes:
  mysql_data:
  grafana_data:
  backend_data:
networks:
  net: